server:
  port: 9163

spring:
  application:
    name: CommunicationMS
  kafka:
    consumer:
      bootstrap-servers:
        - matchit-kafka:9092
      group-id: matchit
    topic-name: "com-matchit"

  mail:
    base-url: http://matchit-frontend:4200
    host: smtp.gmail.com
    port: 587
    username: noreply@we-it.co
    password: WefounD-69002
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  messages:
    basename: i18n/messages

eureka:
  client:
    service-url:
      defaultZone: http://matchit-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
