server:
  port: ${COMMUNICATION_MS_PORT}

spring:
  application:
    name: CommunicationMS
  kafka:
    consumer:
      bootstrap-servers:
        - ${KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      group-id: matchit
    topic-name: "com-matchit"

  mail:
    base-url: ${GKE_FRONTEND_EXTERNAL_ADDRESS}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: ${MAIL_HOST}

  messages:
    basename: i18n/messages

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
