server:
  port: 9163

spring:
  application:
    name: CommunicationMS
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: matchit
    topic-name: "com-matchit"

  mail:
    base-url: http://localhost:4200
    host: smtp.ionos.fr
    port: 587
    username: noreply@match-it.fr
    password: MatchiT-69002
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.ionos.fr

  messages:
    basename: i18n/messages

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
