server:
  port: ${EUREKA_PORT}

spring:
  application:
    name: EurekaMS
  cloud:
    config:
      enabled: true

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE} 
