server:
  port: ${GATEWAY_MS_PORT}

spring:
  application:
    name: GatewayMS
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/api/**]':
            allowedOrigins:
              - https://match-it.fr
              - http://localhost:4200
              - ${GKE_FRONTEND_EXTERNAL_ADDRESS}
            allowedHeaders:
              - Authorization
              - Content-Type
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
      routes:
        - id: route-account-management
          uri: http://${ACCOUNT_SVC_NAME}
          predicates:
            - Path=/api/account/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: route-sourcing-management
          uri: http://${SOURCING_SVC_NAME}
          predicates:
            - Path=/api/sourcing/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_OAUTH2_JWT_ISSUER_URI}
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true

keycloak:
  realm: ${KEYCLOACK_REALM}
  auth-server-url: ${KEYCLOACK_AUTH_SERVER_URL}
  credentials:
    client-id: ${KEYCLOACK_CREDENTIALS_GWT_CLIENT_ID}
    secret: ${KEYCLOACK_CREDENTIALS_GWT_SECRET}

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
