server:
  port: 9102

spring:
  application:
    name: GatewayMS
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      default-filters:
        - TokenRelay
      routes:
        - id: route-account-management
          uri: lb://AccountManagementMS
          predicates:
            - Path=/api/account/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak-sso:
            issuer-uri: http://185.215.166.203:8090/auth/realms/matchit
        registration:
          GatewayMs:
            provider: keycloak-sso
            client-id: matchit-client
            client-secret: lgiA93HfXeimadoVrnBxgUgV1td25RkY
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
