
server:
  port: 9102
spring:
  cloud:
    gateway:
      routes:
        - id: route-account-management
          uri: lb://AccountManagementMS
          predicates:
            - Path=/account/**
eureka:
 client:
   service-url:
     defaultZone: http://eureka-server:8761/eureka
   fetch-registry: true
   register-with-eureka: true
   enabled: false
