server:
  port: 9102

spring:
  application:
    name: GatewayMS
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
      routes:
        - id: route-account-management
          uri: lb://AccountManagementMS
          predicates:
            - Path=/api/account/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: route-sourcing-management
          uri: lb://SourcingMS
          predicates:
            - Path=/api/sourcing/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          GatewayMs:
            provider: keycloak-sso
            client-id: matchit-gwt-client
            client-secret: 1IIhCehnvqvatDFx3VSyrm2pzK2p570k
        provider:
          keycloak-sso:
            issuer-uri: http://185.215.166.203:8090/auth/realms/matchit
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG