server:
  port: 9102

spring:
  application:
    name: GatewayMS
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/api/**]':
            allowedOrigins:
              - https://match-it.fr
              - http://localhost:4200
            allowedHeaders:
              - Authorization
              - Content-Type
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
      routes:
        - id: route-account-management
          uri: lb://AccountManagementMS
          predicates:
            - Path=/api/account/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: route-sourcing-management
          uri: lb://SourcingMS
          predicates:
            - Path=/api/sourcing/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://185.215.166.203:8090/auth/realms/matchit
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

keycloak:
  realm: matchit
  auth-server-url: http://185.215.166.203:8090/auth
  credentials:
    client-id: matchit-gwt-client
    secret: 1IIhCehnvqvatDFx3VSyrm2pzK2p570k

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
