server:
  port: ${SOURCING_MS_PORT}

spring:
  application:
    name: SourcingMS
  messages:
    basename: i18n/messages
  datasource:
    url: ${SOURCING_MS_DATASOURCE_URL}
    username: ${SOURCING_MS_DATASOURCE_USER}
    password: ${SOURCING_POSTGRES_USER_PASSWORD}
  cloud:
    discovery:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_OAUTH2_JWT_ISSUER_URI}
  web:
    cors:
      allowedOrigins: "*"
      allowedHeaders: "*"
      allowedMethods:
        - GET
        - POST
        - DELETE
        - PUT
        - PATCH
      max-age: 3600
  liquibase:
    change-log: classpath:db/liquibase/master.xml
  #  zipkin:
  #    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG

keycloak:
  realm: ${KEYCLOACK_REALM}
  auth-server-url: ${KEYCLOACK_AUTH_SERVER_URL}
  credentials:
    client-id: ${KEYCLOACK_CREDENTIALS_SOURCING_CLIENT_ID}
    secret: ${KEYCLOACK_CREDENTIALS_SOURCING_SECRET}